### ISSUE TITLE
recategorise place?

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#22]
@thoughtstream @lizmat tl;dr: to be pragmatic, I suggest we recategorise '=place' from a directive to a block. 

`=place` was introduced at the end of the revision process as a 'block level' analogy of the inline `P<>` markup.
This makes sense because quite a bit of text that pulled in should be at a block level and have a TOC entry.

By analogy  with `=alias` it seemed logical to categorise it as a directive.

After experimenting with RakuAST, it is treated as a block (which is the default for unknown block names)

To treat it as a directive would need some changes to the RakuAST parser. Since I do not think a change in category from directive to parser radically changes any paradigm, I suggest we make `=place` a block. Then there will be no need to alter the parser at all.

For instance
```
=place https://raku.org/camelia-logo.png  :caption<Raku's mascot>
```
generates the AST
```
RakuAST::Doc::Block.new(
        type        => "place",
        abbreviated => True,
        paragraphs  => (
          "https://raku.org/camelia-logo.png  :caption<Raku's mascot>
        )
      )
```
while
```
=for place :caption<Raku's mascot>  :alt<A multicoloured butterfly>
= :more<styff>
https://raku.org/camelia-logo.png
```
generates
```
RakuAST::Doc::Block.new(
        type       => "place",
        for        => True,
        config     => ${:alt(RakuAST::QuotedString.new(
          processors => <words val>,
          segments   => (
            RakuAST::StrLiteral.new("A multicoloured butterfly"),
          )
        )), :caption(RakuAST::QuotedString.new(
          processors => <words val>,
          segments   => (
            RakuAST::StrLiteral.new("Raku's mascot"),
          )
        )), :more(RakuAST::QuotedString.new(
          processors => <words val>,
          segments   => (
            RakuAST::StrLiteral.new("styff"),
          )
        ))},
        paragraphs => (
          "https://raku.org/camelia-logo.png\n\n",
        )
      )

**Comment by thoughtstream** [comment]
I disagree with any proposal to reclassify `=place` as a block, instead of a directive,
for three reasons:

### 1. It’s incorrect at a design level.

A block is a container for content. But a `=place` does not contain content; it
contains ___direction___ (to another source of content). Hence, logically, it should
be a directive.

### 2. It makes every renderer harder to implement.

Your examples actually demonstrate this problem. Namely:
```rakudoc
=place https://raku.org/camelia-logo.png  :caption<Raku's mascot>
```
versus
```rakudoc
=for place :caption<Raku's mascot>
https://raku.org/camelia-logo.png
```
The first version produces an AST representation where the caption must
then be re-parsed out of the ‘paragraph’ field, presumably by the renderer.
Whereas the second version produces a representation where the caption
is already correctly identified as ‘config’. Dealing with that inconsistency,
and the extra reparsing work it entails, would impose a nontrivial burden 
on every renderer.

Actually, it imposes two extra burdens. Not only does each renderer
now have to reparse the block content to extract valid config metadata,
they also have to reparse that content to detect ***invalid*** content
such as:
```rakudoc
=place https://raku.org/camelia-logo.png  :caption<Raku's mascot>  # Note: Make sure it’s hi-res
```
...or:
```rakudoc
=for place :caption<Raku's mascot>
P<https://raku.org/camelia-logo.png>
```

### 3. It’s intrinsically inconsistent with the rest of Rakudoc.

Even worse, if we allow abbreviated `place` blocks (and only abbreviated `place` blocks)
to specify metadata options within their content:
```rakudoc
=place https://raku.org/camelia-logo.png  :caption<Raku's mascot>
```
...then, for consistency, we presumably have to allow content metadata
within non-abbreviated `place` blocks as well:
```rakudoc
=for place
https://raku.org/camelia-logo.png  :caption<Raku's mascot>
```

After all, if config metadata is allowed in the content of a `place` block, 
why should it matter how the `place` block was specified?

Which means that each renderer now has to reparse config out of the ‘paragraph’ field 
of the AST representation, _and also_ extract it from the representation’s ‘config’ field.

And we have to explain why “inline” config metadata is allowed for `place`,
but not for any other block type.


Of course, the latter two objections go away if we specify that the contents of a `place` block
must consist of only exactly one URL. In which case the above counter-examples:
```rakudoc
=place https://raku.org/camelia-logo.png  :caption<Raku's mascot>

=place https://raku.org/camelia-logo.png  :caption<Raku's mascot>  # Note: Make sure it’s hi-res

=for place 
https://raku.org/camelia-logo.png :caption<Raku's mascot>

=for place :caption<Raku's mascot>
P<https://raku.org/camelia-logo.png>
```
...all become invalid Rakudoc, and any `place` block that requires metadata can no longer
be specified with `=place` (i.e. you have to use `=for place` or `=begin place`...`=end place`).

However, such a draconian restriction of block content is unusual in Rakudoc. 
Every other block type in the language can contain arbitrary amounts of content, 
and every other block type (except `table`) can also contain arbitrary kinds of content. 
Hence, a block that is restricted to exactly one item of content of a very specific kind
...isn’t very blocklike.

And, finally, none of the above musing address the more fundamental design objection:
that _“blocks contain content, but a `place` URL isn’t content; it’s direction”_


So, I’m not enthusiastic about reclassifying `=place` as a block instead of a directive.
I've never been a fan of doing the easy (but wrong) thing, if it's possible to do the
right (but harder) thing.

However, that's an easy philosophical position to hold when one won't actually be  
responsible for doing _either_ thing. As I won’t ever have to fix the AST parser 
to detect `=place` as a directive, nor would I have to fix all the existing and future 
renderers to deal with the special-case inconsistencies of `=place` as a block, 
I’m not sure how much my opinion on this matter should actually count. :-)

**Comment by lizmat** [comment]
I'll have a stab at implementing it as a directive after doing the weekly.

@finanalyst Are there other things I could / should be looking at while I'm in that neck of the woods?

**Comment by thoughtstream** [comment]
> I'll have a stab at implementing it as a directive after doing the weekly.

Thanks @lizmat! You're amazing. :-)

And thanks @finanalyst...for raising the issue in the first place.

You have no idea just how grateful I am that the two of you are willing to channel 
so much of your remarkable energy, and so much of your exceptional talents and abilities, 
into this project.

**Comment by finanalyst** [comment]
@thoughtstream thank you for the response. @lizmat thank you for the extra time.
In due course, I would be very grateful if you could look at [RakuAST Rakudoc Render](https://github.com/finanalyst/rakuast-rakudoc-render). I am slowly getting there, so it is still very much in draft form (I tend to be a cultivate-type worker, than a design-type one). However, I think the overall shape of the module is now visible. I haven't worked on the documentation for the Render part, so usage can be found in the tests. 
@lizmat I'll put together a list of things in next post here.

**Comment by finanalyst** [comment]
@lizmat briefly, of the directives, `=place`, `=column`, `=row`, `=finish` need some TLC
`=finish` has a minor glitch, `=column` and `=row` outside a `=table` should be errors, but I'm 
not sure whether this should be the Parser or Renderer.
A `=table` with `=column`/`=row` yields an AST, and seems to be missing things, but this may be me not knowing enough.

# Detail

**place**
As in this issue, so no more detail here


**finish**
`=finish` causes an error in the following (but otherwise =finish seems to work as expected)
```
=begin rakudoc
RakuDoc text
=end rakudoc
=finish
This is some text
OK
```
produces
```
$ RAKUDO_RAKUAST=1 raku tmp/test.raku
===SORRY!===
Cannot find method 'replace-finish-content' on object of type NQPMu
$ raku tmp/test.raku
$
```
The problem for the RakuAST is cured by adding an instance of `$=finish`, eg,
```
=begin rakudoc
RakuDoc text
=end rakudoc
say $=finish;
=finish
This is some text
OK
```

**table**
See attached 
[test.zip](https://github.com/Raku/RakuDoc-GAMMA/files/14634175/test.zip) which contain
- test.rakudoc
- test.html = test.rakudoc rendered using `Pod::To::HTML2 `
- dump = AST of test.rakudoc

`test.rakudoc` starts 
```
=begin rakudoc
some text

=column :label

=row :label

=begin table :caption<tabula>
    =row :header
```
Outside the block scope of  `=table` , the following should throw errors `=column`, `=row`, `=cell`. 
I dont know whether this should be the Parser or the Renderer's job. 

`dump` has the AST of the table in RakuDoc document, and `test.html` has my rendering of `test.rakudoc` from `$=pod`. 

I do not know how to turn the AST from the table into the HTML. :(
The `:label` options are not included anywhere in the AST
I haven't looked at the `:row-span` or `:col-span` options yet.

Maybe `=table` needs an issue of its own.

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/b82fa83db0 categorizes `=place` as a directive

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/f997c36cc0 fixes the `=finish` issue.

**Comment by lizmat** [comment]
> Outside the block scope of  =table , the following should throw errors =column, =row, =cell.
I dont know whether this should be the Parser or the Renderer's job.

As far as my understanding goes, `=table` is a block, **not** a directive.  Having the parser throw an error about a directive being out of place because of a block, means treating some blocks (in this case`=table`) different from other blocks.  And that feels like damaging the generality and extensibility of the parser to me.

So I feel that this is a renderer issue.

**Comment by lizmat** [comment]
> dump has the AST of the table in RakuDoc document, and test.html has my rendering of test.rakudoc from $=pod.

I would advise against using `$=pod` for this.  Or was that a typo, and did you mean `$=rakudoc` ?

**Comment by lizmat** [comment]
> I do not know how to turn the AST from the table into the HTML. :(
The :label options are not included anywhere in the AST
I haven't looked at the :row-span or :col-span options yet.
Maybe =table needs an issue of its own.

I think it needs a separate issue.  Looks to me now that the whole new table design is mostly NYI.  @finanalyst could you give me a tree of RakuAST objects that you would like to see produced from the `test.rakudoc` document?

**Comment by finanalyst** [comment]
@lizmat 
seems `=finish` issue fixed but `=place` is not working
I put the following into `tmp/test.rakudoc`
```
    =begin rakudoc
    =head1 Head One

    Some text

    =for place :caption<TOC>
    toc:

    More text

    =head1 Head Two

    Again text

    =head2 level two head

    Final stuff

    =end rakudoc
```
Then I get the following in a terminal
```
$ raku -v
Welcome to Rakudo™ v2024.02-93-gc49e05d84.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2024.02.
richard@ged:~/development/rakuast-rakudoc-render$ raku -c tmp/test.rakudoc 
Syntax OK
richard@ged:~/development/rakuast-rakudoc-render$ RAKUDO_RAKUAST=1 raku -c tmp/test.rakudoc 
===SORRY!=== Error while compiling 
Preceding context expects a term, but found infix = instead.
Did you make a mistake in Pod syntax?
------> =⏏begin rakudoc
```

**Comment by lizmat** [comment]
The error maybe LTA, but wasn't `=for place` supposed to be illegal on account of the fact that it is a directive?

**Comment by thoughtstream** [comment]
> wasn't `=for place` supposed to be illegal on account of the fact that `=place` is a directive?

Yes. Or at least: I hope so!

**Comment by finanalyst** [comment]
closing as resolved
