### ISSUE TITLE
allowing single character for 'num'

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#29]
After some discussion, we agreed to remove (going from V1 to V2) `#` as a single character marker to signify numbered blocks (eg. head/item/defn). 
The problems were
- '#' is too heavily overloaded with comment
- but also `#` was defined in the post block name position and could be used in an abbreviated form

To allow for abbreviated forms, we invented `numXXX` where XXX is a block name. Although I think it was a suggestion of mine, it has always irked me as being prolix.

Suppose we accept a single character as a sort of alias of `num`?

I looked at the printable ASCII chars (as they are easily available on nearly all keyboard layouts), and I thought `&` might be good. ( `&` means 'and', with the mnemonic that we have a block & some numbering)

The suggestion is that the following would be both acceptable and equivalent:
```
=numhead     =&head
=numitem      =&item
=numdefn      =&defn
```
As a regular user of `=item` in documentation, I would far prefer to write `=&item` than `=numitem`.

I think that this should be fairly easy to implement both for the parser and the renderer.

For `=config` blocks I dont see a problem with eg
```
=config &head :caption<numbered heading>
```
@thoughtstream @lizmat thoughts?

**Comment by lizmat** [comment]
If we're looking for a shortcut for "num", then I think `+` would be more appropriate and consistent with the use of `+` as a prefix coercer, so: `=+head`, `=+item`, `=+defn`

**Comment by thoughtstream** [comment]
I can't say I'm keen on either `=&head`/`=&item`/`=&defn`or `=+head`/`=+item`/`=+defn`.
I just can't see adding back in a second syntax as being a good idea
(though I agree with @lizmat that the latter is better than the former).

If I had to pick such a syntax, I'd probably go with `=#head`/`=#item`/`=#defn`, 
but even those seem iffy to me.

I guess I'm just not convinced that any of these not-at-all obvious syntactic complications
is worth saving a whole two characters per block, over the much more self-documenting, self-explanatory,
highly readable, consistent-with-the-rest-of-the-language existing syntax: `=numhead`/`=numitem`/`=numdefn`.

It's my view that we need to prioritize "easy to read" over "easy to write", because (hopefully)
any documentation you're creating will be read far more often than it's written.

That said, I'd still be happy to discuss this issue further and to consider any other arguments 
in favour of your proposal.

**Comment by finanalyst** [comment]
All feedback understandable - I'm happy to acquiesce 

Closing as resolved
