### ISSUE TITLE
embedded markup in E<>

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#38]
@thoughtstream @lizmat 
Another embedding issue. Consider the following specification text
```
The C<E<>> code can also be specified with an alternate display text
(before the entity specification and separated from it by a C<|>).
When an alternate text is specified, it is used if the specified entity
cannot be represented by the renderer (e.g. if the renderer only supports ASCII).

For example:

=begin code :lang<RakuDoc> :allow<B>
Raku makes considerable use of the E<B<left- |> laquo> and E<B<right-double-angle |> raquo> characters.

Raku code often contains the E<B<left- and right-corner |> 0xff62;0xff63> bracketing characters
to avoid using quotes.
=end code

An ASCII-only renderer would then render those like so:

Raku makes considerable use of the left- and right-double-angle characters.

Raku code often contains the left- and right-corner bracketing characters to avoid using quotes.
```
Now `E<>` has the possibility of embedded formatting code.

As I am implementing a text-only rendering, I have found that terminals can sustain coloured output, and virtually all Unicode characters - so long as the Unicode font has been installed.

Consequently, I wonder whether the effort parsing expense needed to allow for the possibility of E<> markup having an alternate rendering just for non-Unicode enabled output is necessary.

I wonder whether we should forbid markup inside E<> codes?

Am I being too simplistic?

**Comment by finanalyst** [comment]
Maybe I was too hasty. `E<B<left- |>laquo>` is accepted by the parser.

**Comment by finanalyst** [comment]
More E problems. Consider the following specification:
```
=for item B<:bullet< E<BALLOT BOX WITH CHECK> >>
Investigate existing solutions
```
The issue came up because $ast.resolve-config, the method for getting the meta options, is not providing the pair bullet=>Unicode code point.

I did not think when considering metadata options there would be any need to embed code within metadata, and so whatever is inside an option would be String. However, here we have `:bullet` with `E<>`.

Liz and I were discussing this on `#raku-dev`.
```
<lizmat> I'm afraid the :bullet<E<foo bar>> thing will need an issue
<lizmat> Do we apply Raku semantics inside the :bullet< >  or not
<lizmat> if we do, then :bullet<E<foo bar>> is the equivalent of bullet => <E<foo bar>>
<lizmat> which is the equivalent of bullet => ('E<foo','bar>')
<lizmat> ± val semantics
```
In order to get `E<>` to work with an alternate rendering, as in first post of this thread, Liz came up with a way to make the meta (or part after the `|`) into a sequence of pairs. 

It seems to me that (and given the AST is in $ast) this means if E has no meta, eg E<BALLOT BOX WITH CROSS>, then the value to be used is just $ast.Str. 
But if E has meta, eg E<SQUARE | BALLOT BOX WITH X> and as would be typical, the Unicode can be used, then the value to be used is `$ast.meta.map(*.value).join` 

Whilst I agree that the alternate rendering possibility allows for custom entities, my own experience is that I would far prefer to be able to customise bullets.

This explanation may be a bit confusing :(

@thoughtstream your input is needed.

**Comment by finanalyst** [comment]
After another conversation with Liz, the issue seems to boil down to the following:
When a metadata option is specified in a RakuDoc block, is the content of the option to be considered with Raku semantics or RakuDoc semantics?

rakudoc_draft_3 says:
```

Metadata is specified using Raku option pairs. The following are examples:

=begin table
 Value is...       Specify with...
 ===============   ===================
 True              :key
 False             :!key
 Literal           :key<answer>
 List              :key("foo", 42)
 Hash              :key{ :note('Rosebud, they said'), :emphasize }
=end table

Numerical values can be specified in any Raku-compatible format
(42, 42.0, 42e0, 0x2a, 0d42, 0o52, 0b101010).  Strings can either be specified
using single or double quotes, or angle brackets (C<'foo'>, C<"bar">, C< <baz> >).
Note that if a string with whitespace is specified in angle brackets, it
is in fact a list of strings: C<< <foo bar baz> >> is the same as C< ('foo','bar','baz') >.
```
Suppose we want to have `:option< %*ENV<RAKUDO_RAKUAST> >` ? Is `V<...>` verbatim markup?

An idea would be to have another marker that indicates the interior is RakuDoc. Maybe 
```
=for item :bullet[ E<BALLOT BOX WITH X> ]
```
Where `[  ]` indicates the content is RakuDoc semantics?

**Comment by thoughtstream** [comment]
My first thought is that we should stick with metaoptions only ever having
Raku semantics. You would then have to specify your bullet with:

```rakudoc
    =for item :bullet("\c[BALLOT BOX WITH CHECK]")
    Investigate existing solutions
```
...or:
```rakudoc
    =for item :bullet«\c[BALLOT BOX WITH CHECK]»
    Investigate existing solutions
```
..or just put the Unicode character in directly:
```rakudoc
    =for item :bullet<☑︎>
    Investigate existing solutions
```

However, I do agree that there are at least two of metaoptions (namely: `:bullet` and `:caption`)
where it would also be convenient to be able to be able to include RakuDoc markup.

But I don’t think that using square-bracket delimiters to impose RakuDoc semantics
is the right approach. Mainly because square-bracket delimiters on a Pair literal
already have special Raku semantics (they make the value an array).

If we were to use a set of delimiters to specify RakuDoc semantics,
it would have to be some other set which aren’t valid in Raku.
Maybe `:bullet「E<SQUARE FOUR CORNERS>」` or `:bullet〔E<turtle>〕`.

Note that, whatever we choose, the delimiters can’t be ASCII or even Latin-1,
because Raku has already appropriated all those parentheses and given them special meanings.

But somehow having a special kind of metaoption parentheses still kinda feels wrong to me, 
for reasons that I can’t even clearly enumerate just at the moment.

I wondered if the right approach might be to specify that, by default, all metadata options
have pure Raku semantics in their values...and then to explicitly make an exception
to that rule only for `:bullet` and `:caption`, which would always treat their
associated value as a pure RakuDoc text sequence, regardless of the identifiers.
I don’t know if that approach would be easy (or even possible) to implement in the parser,
and I’m aware that I’d casually be making things more complicated, even if it is possible.

And it still doesn’t solve the problem perfectly. Because I can also imagine circumstances
where I’d want both `:bullet` and `:caption` to have Raku semantics. For example, so I could
interpolate something (perhaps a module name) into a caption from the ambient Raku code.

So I guess we’re back to _“Metaoption data is always parsed with Raku semantics, unless
it has the special delimiters that indicate RakuDoc semantics instead.”_

And at this point, I’d ***really*** like to hear what Liz has to say
about any of those alternatives. :-)

**Comment by finanalyst** [comment]
@thoughtstream on IRC @lizmat suggested `:bullet=(E<BALLOT BOX WITH X>)` but wondered about how to implement it.

I'm interested in what she has to say after thinking about it.

**Comment by lizmat** [comment]
I've now tried to get the `:bullet=(E<BALLOT BOX WITH X>)` syntax working, and it fails.

The token I used: `':' <ident> '=(' $<rakudoc>=<-[)]>* ')'`.  Works fine in regexes, but inside the Raku grammar, it's a no go.

This is going to take days to figure out (unless @thoughtstream has some ideas).

FWIW, I think the workaround `:bullet«\c[BALLOT BOX WITH CHECK]»`, which results in:
```raku
    config     => ${:bullet(RakuAST::QuotedString.new(
      processors => <quotewords val>,
      segments   => (
        RakuAST::StrLiteral.new("☑"),
      )
    ))}
```
is very acceptable and in line with expectations and Raku semantics.

So I'd say: no special cases.  And only Raku semantics in configs.

**Comment by thoughtstream** [comment]
I can see the design thinking behind adding a `:option=()` syntax,
but I’m not in favour of it. It’s a complication, and an inconsistency
with Raku, and not sufficiently useful to balance out those negatives.

So I agree with @lizmat that metaoptions should ***always*** be parsed
with pure Raku semantics.

That said, there are only two metaoptions where allowing
embedded RakuDoc markup even makes sense: `:bullet` and `:caption`.

As regards `:bullet`, we already have a workaround in the form of:
`:bullet<☑︎>` or `:bullet«\c[BALLOT BOX WITH CHECK]»`.

We could also specify that renderers are _permitted_ (but not required)
to support the `E<>` markup code within bullets. Presumably they could
preprocess any bullet specification they receive with something like:

```raku
    $bullet ~~ s:g/ <wb> 'E<'~'>' (<:L+:Z>+) /$0.uniparse()/;
```

As regards `:caption`, I spent some time messing around with the notion
of replacing `:caption` with a `=caption` directive that would allow
markup in the caption, but have concluded that it just doesn’t work,
and that we have to say that captions simply can’t have markup. 
And that they must use the same approach as `:bullet` for including 
any entities/emoji that they may require.

**Comment by finanalyst** [comment]
@finanalyst @lizmat I agree that requiring Raku semantics inside metadata options is the most elegant result.
I also thought about the consequences for non-Raku  implementations of RakuDoc. Such a renderer would need to emulate Raku syntax for inner constructs, and having another set of semantics (RakuDoc) for an exception is not going to make things any easier.

I'll draft a change to the document and put it in a PR.

**Comment by finanalyst** [comment]
resolved
