### ISSUE TITLE
A<|> example incorrect?

### ISSUE THREAD

**Issue by lizmat** [Raku/RakuDoc-GAMMA#42]
https://github.com/Raku/RakuDoc-GAMMA/blob/55b706315dcd92e5657c9a317c2ab449c5713c5a/rakudoc_draft_3.rakudoc#L509-L512

I believe this to be wrong, as the `|` is part of `B<>`, rather than `A<>`.  I believe the example should be:
```
    The use of A<B<this program>| PROGNAME> is subject to the terms and conditions
    laid out by A<B<our company>| VENDOR>, as specified at:


        A<B<(Please visit our website) |> TERMS_URLS>
```
On a related note: having a space before `PROGNAME` and `VENDOR` implies whitespace should be trimmed from the `A<>` key?

**Comment by thoughtstream** [comment]
I believe the example is correct as it stands.

Note that the `=begin code` block surrounding those three lines has an `:allow< B >` option.
So those `B<...>` markups will be invisible (or, rather, will be prerendered) in the output text.

Each `B<...>` is being used to _highlight_ the feature being described 
in the preceding paragraph, ***not*** as an example of actual RakuDoc usage.

In other words, the text is supposed to be rendered:

___

Alias placement codes may also specify a default display text, before the
alias name and separated from it by a `|`. When a display is specified,
it will be used if the requested alias cannot be found (and an _"unknown alias"_
warning will be issued in that case):

<CODE>&nbsp;&nbsp;&nbsp;&nbsp;The use of A\<<STRONG>this program |</STRONG> PROGNAME\> is subject to the terms and conditions</CODE>
<CODE>&nbsp;&nbsp;&nbsp;&nbsp;laid out by A\<<STRONG>our company |</STRONG> VENDOR>, as specified at:</CODE>
<CODE></CODE>
<CODE>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A\<<STRONG>(Please visit our website) |</STRONG> TERMS_URLS></CODE>
</CODE>

___

...thereby hightlighting the instances of a _"default display text, before the alias name and separated from it by a `|`"_.

Of course, in an actual RakuDoc usage of the `A<...>` code, it would definitely be
an error to close the nested `B<...>` after the `|`, instead of before it.

> having a space before PROGNAME and VENDOR implies whitespace should be trimmed from the A<> key?

Yes, IMHO whitespace should be ignored both fore and aft of the alias key.
