### ISSUE TITLE
How to distinguish highlighted code

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#45]
@thoughtstream @coke @lizmat It seems to me that the RakuDoc specification is incomplete / too vague about `code` and highlighting.

@lizmat has created a highlighter based on the AST of Raku code. The highlighter also verifies that the Raku is valid, so an error message can be generated if not. But this creates a problem with the default to `=code` blocks, which by implication (not specification - I think) is Raku.

My proposal is: 
- If a code block has a `:lang` option, then a renderer may apply a syntax highlighter to the code. (The document author then needs to ensure the code is correct)
- If a code block does not have a `:lang` option, then renderer ***may not*** apply a syntax highlighter to the code. (The current default is that if no `:lang`option, it is considered Raku)

The current specification requires an extra option `:syntax-highlighting` to turn off highlighting. I suggested this during the initial conversation on this topic, but my view now is that if a `:lang` is specified, then the author expects highlighting. I also think now that the `:syntax-highlighting` option is eliminated.

Often, a `=code` block is used to render text verbatim. No particular language is intended. However, currently to turn off highlighting, the block needs to be marked with a `:lang` option such as 'text' that inherently has no highlighting.

But this is a change to the implied default. And the specification needs to make this clear.

Thoughts?

**Comment by coke** [comment]
For raku/docs, it's reasonable that the default language is Raku - we assume this default for our code validator - if we have something that is just monospace, we tend to use ```:lang<shell>``` or such. Could we use ```:lang<>``` with an empty lang as shorthand for mono-not-Raku-don't-care ?

**Comment by finanalyst** [comment]
@coke I have seen `:lang<text>` which is why I suggested it as an alternative. The way I've coded `Rakuast::RakuDoc::Render`, any unrecognised 'lang' is verbatim (monospace). 

But `:lang<>` will not work. Empty string must be `:lang('')`, so the shortest would be something like `:lang<?>` or `:lang<*>` or `:lang<z>`.

**Comment by thoughtstream** [comment]
Take the following with an very large grain of salt
_(because I am well known for strongly disliking syntax highlighting in any form)_...

I think the default of assuming Raku when no `:lang` is specified is entirely appropriate.
After all, it _is_ ***Raku***Doc, not ***Text***Doc.

And if an author wants to default to no markup, all they (currently) need to do 
is add a single line to the start of their file:
```rakudoc
=config code :lang<text>
```
...or:
```rakudoc
=config code :!syntax-highlighting
```
...depending on whether they want to disable syntax highlighting because their "code" is not code,
or because of their entirely rational hatred of syntax highlighting. ;-)

I ***can*** see the argument for having a form of `:lang` option that indicates "no language",
and I suspect `:lang<text>` isn't ideal for that purpose. Personally I would have thought 
that `:!lang` is the correct form.

But even with `:!lang` available to disable language identification (and hence syntax highlighting)
on any block, I still think there is a need for `:!syntax-highlighting` as well. Because, in the future,
the `:lang` annotation on a `=code` block might be used for more than just syntax highlighting.

For example, I can imagine a tool that extracts the contents of each `=code` block
and syntax checks those contents to ensure the code is valid. Such a tool might use
the `:lang` annotations to determine which `=code` blocks to validate _(e.g. only blocks
marked as Raku code)_, or alternatively it might use the `:lang` value to find an appropriate
validator for multiple languages.

But those kinds of additional uses of the `:lang` value are entirely orthogonal 
to whether or not I want a particular `=code` block to be syntax-highlighted.
Particularly if the code in that block is deliberately wrong...in which case
syntax highlighting will presumably either not work correctly (or at all), 
or else may itself be counterproductive or misleading.

For example, I can readily imagine writing something like:

```rakudoc
    A common mistake when starting out with Raku is to unconsciously apply the syntax
    of an older but similar language with which the novice Raku programmer is more familiar,
    such as Perl:

    =begin code :lang<raku> :!syntax-highlightling

        my $name = get_first() . get_second();    # NOT a string concatenation
        my $id   = lookup -> {$name};             # NOT a hash lookup

    =end code
```

Here I specifically want to mark the contents as Raku code, but don't want them
syntax-highlighted as Raku code, in order to reinforce the ambiguity of the code.

In light of all the above, I would propose we explicitly specify:

* `=code` blocks with no explicit or preconfigured `:lang` option default to `:lang<raku>`
* `=code` blocks can be marked as not being in any specific language by using `:!lang`
* Renderers must not syntax-highlight any code block whose `:lang` value is `False`
* Renderers must not syntax-highlight any code block whose `:syntax-highlighting` value is `False`
* Renderers may syntax-highlight any other code block (including `:lang<text>`), but are not required to do so

**Comment by finanalyst** [comment]
closing as resolved
