### ISSUE TITLE
Application of `:error` and other configurations globally

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#56]
@thoughtstream In #52 we discussed adding the option `:error` / `:!error` to custom blocks.
More generally, the specification indicate that how and when errors are generated is left to the renderer.
We have not specified how to affect this within the document.
One of the ideas I included in `Raku::Pod::Render` is that when a meta option is included in the `=begin rakudoc` block, then it is treated document meta data and provided to all blocks as a default. 
A `=config` statement is directed to a named Block. I do not want to suggest that the block name can be replaced by a regex. I think that would be too powerful at present.
Suppose an author wants to turn off all error statements, then perhaps we could allow
```
=begin rakudoc :!error :alt<contact document author>
```
These would be the default for all blocks, and over-ridden if given by a config or the block option.

**Comment by thoughtstream** [comment]
I am extremely wary of allowing any metaoption on an outer block to affect other blocks 
(even just those that are nested inside the outer block).

I also worry that we're multiplying entities without necessity, since we already have a mechanism
(_i.e._ `=config`) for lexically preconfiguring blocks.

The problem, as you point out, is that this mechanism currently doesn't allow generic configuration
of all block types, only specific configuration of a single block type. And, as you say, the obvious
extension would be to allow the target block type to be specified via a regex, in which case we could
simply configure every block with:
```
=config  /.*/  :!error :alt<contact document author>
```
Allowing regexes as `=config` targets would have many other advantages too. 
For example, we could then configure multiple nested list item levels to all use the same bullet:
```
=config  /^item<[1..4]>/  :bullet« \c[CIRCLED BULLET] »
```
Or configure all four "literal" formatting codes to allow nested _Basis_ codes:
```
=config  /C|V|K|T/  :allow<B>
```

But I agree that supporting regexes as `=config` targets might require too much effort at the moment,
and that the idea may be better left to RakuDoc v3.

However, I don't see why we couldn't at least support a single _"universal target"_ for `=config`;
specifically, by allowing the target name to be a `Whatever`. So your universal `:alt` tag example
could be written:
```
=config  *  :!error :alt<contact document author>
```

**Comment by finanalyst** [comment]
@thoughtstream A single '*' would be consistent with other RakuDoc elements. 
- I'll add a PR in due course for the Spec if its easy to implement (which I think it should be)
- I'll add the regex idea to the V3 list

**Comment by finanalyst** [comment]
@thoughtstream @lizmat 
> `=config  *  :!error :alt<contact document author>`
Unfortunately a '*' in this position causes a compile error.
```
 raku -e '"=begin rakudoc\n=config * :one :two\n=end rakudoc".AST.say'
===SORRY!=== Error while compiling /home/richard/development/rakuast-rakudoc-render/EVAL_0
Preceding context expects a term, but found infix = instead.
```

May be the pseudo block 'any'?

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/3f0f974e4b allows `*` as identifier in `=config`

**Comment by finanalyst** [comment]
@lizmat you are a genius !

**Comment by thoughtstream** [comment]
> @lizmat you are a genius !

Indeed! Outstanding work (as usual :-)

**Comment by finanalyst** [comment]
closing as resolved
